version: "3.8"

services:
  node_app:
    build: ./
    container_name: node_app
    ports:
      - "4000:4000"   # map trực tiếp port host 80 → container 4000
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
